# GitLab CI/CD Template: Python Projects
# =========================================
# Complete pipeline for Python projects using Poetry for dependency management.
# Includes linting (ruff), type checking (mypy), and testing (pytest).
#
# Usage:
#   include:
#     - project: 'your-group/mai-gitlab-skill'
#       ref: main
#       file: '/Templates/python.yml'
#
# Variables:
#   PYTHON_VERSION  - Python version (default: 3.12)
#   POETRY_VERSION  - Poetry version (default: 1.8.0)
#
# Supports both Poetry and pip workflows. Set USE_PIP=true for pip-only projects.

default:
  image: python:3.12-slim
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

stages:
  - install
  - lint
  - test
  - build
  - deploy

variables:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "1.8.0"
  # Disable pip warnings about running as root
  PIP_ROOT_USER_ACTION: "ignore"
  # Poetry configuration
  POETRY_HOME: "/opt/poetry"
  POETRY_VIRTUALENVS_CREATE: "true"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  POETRY_NO_INTERACTION: "1"
  # Use pip instead of Poetry
  USE_PIP: "false"

# ------------------------------------------------------------------------------
# Cache Configuration
# ------------------------------------------------------------------------------
cache:
  key:
    files:
      - poetry.lock
      - pyproject.toml
      - requirements.txt
    prefix: ${CI_COMMIT_REF_SLUG}
  paths:
    - .venv/
    - .cache/pip/
  policy: pull-push

# ------------------------------------------------------------------------------
# Before Script: Install Poetry
# ------------------------------------------------------------------------------
.poetry_setup:
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends curl git
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="${POETRY_HOME}/bin:$PATH"
    - poetry --version

.pip_setup:
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

# ------------------------------------------------------------------------------
# Install Stage
# ------------------------------------------------------------------------------
install:
  stage: install
  extends: .poetry_setup
  script:
    - export PATH="${POETRY_HOME}/bin:$PATH"
    - echo "Installing dependencies with Poetry..."
    - poetry install --no-root
    - echo "Dependencies installed successfully"
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour
  rules:
    - if: $USE_PIP == "true"
      when: never
    - when: always

install-pip:
  stage: install
  extends: .pip_setup
  script:
    - echo "Installing dependencies with pip..."
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt || true
    - echo "Dependencies installed successfully"
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour
  rules:
    - if: $USE_PIP == "true"
    - when: never

# ------------------------------------------------------------------------------
# Lint Stage
# ------------------------------------------------------------------------------
# Uses ruff for fast Python linting (replaces flake8, isort, pyupgrade, etc.)
lint:
  stage: lint
  extends: .poetry_setup
  needs:
    - job: install
      optional: true
    - job: install-pip
      optional: true
  script:
    - export PATH="${POETRY_HOME}/bin:$PATH"
    - echo "Running ruff linter..."
    - poetry run ruff check . --output-format=gitlab
    - echo "Running ruff formatter check..."
    - poetry run ruff format --check .
  allow_failure: true
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Type checking with mypy
typecheck:
  stage: lint
  extends: .poetry_setup
  needs:
    - job: install
      optional: true
    - job: install-pip
      optional: true
  script:
    - export PATH="${POETRY_HOME}/bin:$PATH"
    - echo "Running mypy type checker..."
    - poetry run mypy . --ignore-missing-imports
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# ------------------------------------------------------------------------------
# Test Stage
# ------------------------------------------------------------------------------
test:
  stage: test
  extends: .poetry_setup
  needs:
    - job: install
      optional: true
    - job: install-pip
      optional: true
  script:
    - export PATH="${POETRY_HOME}/bin:$PATH"
    - echo "Running pytest..."
    - poetry run pytest --cov=. --cov-report=xml --cov-report=html --junitxml=junit.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - htmlcov/
      - coverage.xml
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

# ------------------------------------------------------------------------------
# Build Stage
# ------------------------------------------------------------------------------
# Builds Python package using Poetry
build:
  stage: build
  extends: .poetry_setup
  needs:
    - job: install
      optional: true
    - job: test
      optional: true
  script:
    - export PATH="${POETRY_HOME}/bin:$PATH"
    - echo "Building package..."
    - poetry build
    - ls -la dist/
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

# ------------------------------------------------------------------------------
# Deploy Templates
# ------------------------------------------------------------------------------
# Publish to PyPI (or private registry)
.publish_pypi:
  stage: deploy
  extends: .poetry_setup
  needs:
    - build
  script:
    - export PATH="${POETRY_HOME}/bin:$PATH"
    # Configure PyPI credentials from CI variables
    - poetry config pypi-token.pypi ${PYPI_TOKEN}
    - poetry publish
  rules:
    - if: $CI_COMMIT_TAG
      when: manual

# Publish to GitLab Package Registry
.publish_gitlab:
  stage: deploy
  extends: .poetry_setup
  needs:
    - build
  script:
    - export PATH="${POETRY_HOME}/bin:$PATH"
    # Configure GitLab Package Registry
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry publish --repository gitlab --username gitlab-ci-token --password ${CI_JOB_TOKEN}
  rules:
    - if: $CI_COMMIT_TAG

# Generic deploy template
.deploy:
  stage: deploy
  extends: .poetry_setup
  needs:
    - build
  script:
    - echo "Override this script in your project"
    - echo "Example: poetry run deploy"
  environment:
    name: $CI_COMMIT_REF_SLUG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

# ------------------------------------------------------------------------------
# Utility Templates
# ------------------------------------------------------------------------------

# Template for jobs that need database access
.with_postgres:
  services:
    - postgres:15-alpine
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_password
    DATABASE_URL: "postgresql://test_user:test_password@postgres:5432/test_db"

# Template for jobs that need Redis
.with_redis:
  services:
    - redis:7-alpine
  variables:
    REDIS_URL: "redis://redis:6379"
