/**
 * The mobile interface's anti-drift test.
 *
 * These assertions are the mechanical form of "same information, same
 * structure": every page the desktop nav offers must be reachable on mobile,
 * every mobile route file must be a pure re-export of its desktop page (so it
 * has no markup that COULD drift), and navigation must be read from the shared
 * manifest rather than restated.
 *
 * Run: cd LIFEOS/PULSE/Observability && bun test
 */

import { describe, expect, test } from "bun:test";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const SRC = join(import.meta.dir, "..", "src");
const M_TREE = join(SRC, "app", "m");
const MANIFEST = join(SRC, "lib", "palette", "nav-manifest.ts");

function walk(dir: string, match: RegExp): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) out.push(...walk(p, match));
    else if (match.test(entry)) out.push(p);
  }
  return out;
}

const manifestSrc = readFileSync(MANIFEST, "utf-8");
const manifestHrefs = [...manifestSrc.matchAll(/href:\s*"([^"]+)"/g)].map((m) => m[1]);

/** Hand-written mobile sources — the shell, its CSS, the nav derivation. */
const handWritten = [
  ...walk(join(SRC, "components", "mobile"), /\.(tsx?|css)$/),
  ...walk(join(SRC, "lib", "mobile"), /\.tsx?$/),
  join(SRC, "contexts", "DensityContext.tsx"),
];

/** Generated route files. */
const generated = walk(M_TREE, /^(page|layout)\.tsx$/).filter((f) =>
  readFileSync(f, "utf-8").startsWith("// Generated by")
);

describe("mobile route coverage", () => {
  test("nav manifest is non-empty (guards the regex above)", () => {
    expect(manifestHrefs.length).toBeGreaterThan(20);
  });

  test("every nav-manifest page that EXISTS on desktop is reachable on mobile", () => {
    // Gated on the desktop page existing, deliberately. The mobile tree mirrors
    // the desktop; it cannot invent a page the install doesn't ship. The public
    // LifeOS repo, for instance, lists /projects and /security in the manifest
    // but carries neither page.tsx — those entries are already dead links on
    // desktop there, and mobile correctly declines to fabricate them.
    const missing = manifestHrefs.filter((href) => {
      const desktop = href === "/" ? join(SRC, "app", "page.tsx") : join(SRC, "app", href.slice(1), "page.tsx");
      if (!existsSync(desktop)) return false;
      const mobile = href === "/" ? join(M_TREE, "page.tsx") : join(M_TREE, href.slice(1), "page.tsx");
      return !existsSync(mobile);
    });
    expect(missing).toEqual([]);
  });

  test("every mobile route file is a pure re-export of its desktop page", () => {
    // No JSX, no hooks, no data — nothing that could say something different
    // from the desktop page it stands in for. The TELOS section routes are the
    // one exception (they mount a shared section, not a whole desktop page)
    // and get their own assertion below.
    const impure = generated
      .filter((f) => !/[/\\]m[/\\]telos[/\\][^/\\]+[/\\]page\.tsx$/.test(f) || f.includes("item"))
      .filter((f) => {
        const body = readFileSync(f, "utf-8")
          .split("\n")
          .filter((l) => l.trim() && !l.trim().startsWith("//"))
          .join("\n");
        return !/^export \{ default \} from "@\/app\/[^"]+";$/.test(body.trim());
      });
    expect(impure.map((f) => relative(SRC, f))).toEqual([]);
  });

  test("TELOS section routes are generated wrappers with no markup of their own", () => {
    const sectionRoutes = generated.filter(
      (f) => /[/\\]m[/\\]telos[/\\][^/\\]+[/\\]page\.tsx$/.test(f) && !f.includes("item")
    );
    expect(sectionRoutes.length).toBeGreaterThanOrEqual(12);
    const impure = sectionRoutes.filter((f) => {
      const s = readFileSync(f, "utf-8");
      return !/return <TelosSectionView slug="[a-z]+" \/>;/.test(s);
    });
    expect(impure.map((f) => relative(SRC, f))).toEqual([]);
  });

  test("the generated tree is current", async () => {
    const proc = Bun.spawnSync({
      cmd: ["bun", join(import.meta.dir, "..", "scripts", "gen-mobile-routes.ts"), "--check"],
      cwd: join(import.meta.dir, ".."),
    });
    expect(proc.stderr.toString() + proc.stdout.toString()).toContain("current");
    expect(proc.exitCode).toBe(0);
  });
});

describe("TELOS sections are one list, two surfaces", () => {
  const manifestPath = join(SRC, "app", "telos", "_v7", "section-manifest.ts");
  const registryPath = join(SRC, "app", "telos", "_v7", "section-registry.tsx");
  const appPath = join(SRC, "app", "telos", "_v7", "app.tsx");
  const navPath = join(SRC, "lib", "mobile", "nav.ts");

  const manifest = readFileSync(manifestPath, "utf-8");
  const registry = readFileSync(registryPath, "utf-8");
  const slugs = [...manifest.matchAll(/slug:\s*"([^"]+)"/g)].map((m) => m[1]);

  test("the manifest has the sections the TELOS view is made of", () => {
    expect(slugs.length).toBeGreaterThanOrEqual(12);
    expect(new Set(slugs).size).toBe(slugs.length); // no duplicate slugs
  });

  test("every manifest section has a renderer — none silently vanishes", () => {
    // TELOS_SECTIONS filters to slugs with renderers, so a missing one would
    // drop the section off both the desktop stack and the mobile menu quietly.
    const missing = slugs.filter((s) => !new RegExp(`^\\s{2}${s}:\\s*\\(c\\)`, "m").test(registry));
    expect(missing).toEqual([]);
  });

  test("the manifest stays server-importable (no 'use client')", () => {
    // generateStaticParams runs on the server; a client module's exports would
    // arrive there as opaque references. This bit us once — keep it bitten.
    // The directive, not the word — the file's own comment explains why it
    // must not be a client module, and that comment is not a violation.
    expect(manifest).not.toMatch(/^\s*["']use client["']/);
    // The generator imports it at build time, outside any React runtime.
    expect(readFileSync(join(import.meta.dir, "..", "scripts", "gen-mobile-routes.ts"), "utf-8"))
      .toContain("section-manifest");
  });

  test("the desktop stack renders from the registry, not its own list", () => {
    const app = readFileSync(appPath, "utf-8");
    expect(app).toContain("TelosSectionStack");
    // The old inline stack would show up as direct section JSX in app.tsx.
    expect(app).not.toMatch(/<(Problems|MissionGoals|Metrics|ChallengeStrategy|Team|Budget|Recommendations|Stranded|SubTabs|Preferences)\b/);
  });

  test("the burger menu lists every section, derived not restated", () => {
    const nav = readFileSync(navPath, "utf-8");
    expect(nav).toContain("TELOS_SECTION_META.map");
    for (const s of slugs) expect(nav).not.toContain(`"${s}"`); // no hardcoded slug list
  });

  test("one STATIC route per section exists", () => {
    const missing = slugs.filter((s) => !existsSync(join(SRC, "app", "m", "telos", s, "page.tsx")));
    expect(missing).toEqual([]);
  });

  test("no dynamic [section] route — it hydrated into a client-side exception", () => {
    // Regression guard for a bug that shipped 200s on all twelve paths while
    // every one of them died in the browser. Error boundaries around the
    // section body and around the whole route both failed to catch it; the
    // neighbouring static route /m/telos/item was fine throughout. Static
    // routes are the fix, and this test is why it stays fixed.
    expect(existsSync(join(SRC, "app", "m", "telos", "[section]"))).toBe(false);
  });

  test("the mobile index replaces the twelve-section scroll", () => {
    const index = readFileSync(join(SRC, "app", "m", "telos", "page.tsx"), "utf-8");
    expect(index).toContain("TelosIndex");
    expect(index).not.toContain("@/app/telos/page");
  });
});

describe("plane switching preserves what identifies the thing you are looking at", () => {
  // Regression guard. A tapped Knowledge entry links to
  // `/knowledge?category=research&slug=…`; the redirect used to rebuild that as
  // `/m/knowledge`, dropping the query, so the note silently became the index.
  // Reported as "I cannot see an entry".
  test("toMobilePath / toDesktopPath keep query and hash", async () => {
    const { toMobilePath, toDesktopPath } = await import("../src/lib/mobile/config");
    expect(toMobilePath("/knowledge?category=research&slug=x")).toBe("/m/knowledge?category=research&slug=x");
    expect(toMobilePath("/?a=1")).toBe("/m?a=1");
    expect(toMobilePath("/telos/item?id=G0#notes")).toBe("/m/telos/item?id=G0#notes");
    expect(toDesktopPath("/m/knowledge?category=research&slug=x")).toBe("/knowledge?category=research&slug=x");
    expect(toDesktopPath("/m?a=1")).toBe("/?a=1");
    // Plain paths must be untouched.
    expect(toMobilePath("/work")).toBe("/m/work");
    expect(toDesktopPath("/m/work")).toBe("/work");
    expect(toDesktopPath("/work")).toBe("/work");
  });

  test("the generated route list drives link rewriting and includes hand-written routes", async () => {
    const { MOBILE_ROUTES } = await import("../src/lib/mobile/routes.generated");
    const { isMobileablePath } = await import("../src/lib/mobile/config");
    // "" (home) and "telos" are HAND_WRITTEN, so the generator does not emit
    // their page files and must add them to the list explicitly.
    expect(MOBILE_ROUTES).toContain("");
    expect(MOBILE_ROUTES).toContain("telos");
    expect(MOBILE_ROUTES).toContain("knowledge");
    // A path with a mobile route is rewritten; one without is left alone so it
    // reaches a working desktop page instead of a 404.
    expect(isMobileablePath("/knowledge?slug=x", MOBILE_ROUTES)).toBe(true);
    expect(isMobileablePath("/definitely-not-a-route", MOBILE_ROUTES)).toBe(false);
  });
});

describe("mobile layer stays a presentation layer", () => {
  test("no data fetching is re-implemented on the mobile side", () => {
    const offenders = handWritten.filter((f) => /fetch\(\s*["'`]\/api\//.test(readFileSync(f, "utf-8")));
    expect(offenders.map((f) => relative(SRC, f))).toEqual([]);
  });

  test("navigation is derived from the manifest, never restated", () => {
    const nav = readFileSync(join(SRC, "lib", "mobile", "nav.ts"), "utf-8");
    expect(nav).toContain('from "@/lib/palette/nav-manifest"');
    const literals = handWritten.filter((f) => /href:\s*"\/[a-z]/.test(readFileSync(f, "utf-8")));
    expect(literals.map((f) => relative(SRC, f))).toEqual([]);
  });

  test("the hand-written mobile layer is small relative to what it presents", () => {
    // Bound raised 900 → 1200 on 2026-07-29 when the TELOS section-per-page
    // treatment was added (index + section host + their CSS). Raised
    // deliberately and recorded in the ISA Changelog — never silently, because
    // this bound is the whole defence against the mobile layer quietly
    // becoming a second copy of Pulse. It presents 11,303 lines of pages.
    const lines = handWritten.reduce((n, f) => n + readFileSync(f, "utf-8").split("\n").length, 0);
    expect(lines).toBeLessThan(1200);
  });

  test("no absolute user-home paths leak into source", () => {
    const offenders = [...handWritten, ...generated].filter((f) => /\/home\/[a-z]/.test(readFileSync(f, "utf-8")));
    expect(offenders.map((f) => relative(SRC, f))).toEqual([]);
  });
});
