# GitLab CI/CD Template: Node.js / Bun Projects
# ================================================
# Complete pipeline for Node.js/Bun projects with caching, linting, testing, and building.
#
# Usage:
#   include:
#     - project: 'your-group/kai-gitlab-skill'
#       ref: main
#       file: '/Templates/nodejs.yml'
#
# Variables:
#   NODE_ENV      - Node environment (default: production)
#   BUN_VERSION   - Override by changing image tag
#
# Extend .deploy for custom deployment logic.

default:
  image: oven/bun:1
  # Retry failed jobs once (handles transient network issues)
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

stages:
  - install
  - lint
  - test
  - build
  - deploy

variables:
  NODE_ENV: "production"
  # Bun cache directory for faster installs
  BUN_INSTALL_CACHE_DIR: ".bun/install/cache"

# ------------------------------------------------------------------------------
# Cache Configuration
# ------------------------------------------------------------------------------
# Uses branch-specific caching to avoid conflicts between branches.
# Falls back to default branch cache if no branch-specific cache exists.
cache:
  key:
    files:
      - bun.lockb
      - package.json
    prefix: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .bun/
  policy: pull-push

# ------------------------------------------------------------------------------
# Install Stage
# ------------------------------------------------------------------------------
# Installs dependencies and creates artifacts for subsequent stages.
# Uses --frozen-lockfile to ensure reproducible builds.
install:
  stage: install
  script:
    - echo "Installing dependencies with Bun..."
    - bun install --frozen-lockfile
    - echo "Dependencies installed successfully"
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour
  # Only run when dependency files change (optimization)
  rules:
    - changes:
        - package.json
        - bun.lockb
      when: always
    - when: always

# ------------------------------------------------------------------------------
# Lint Stage
# ------------------------------------------------------------------------------
# Runs linting checks. Allowed to fail to not block builds on style issues.
# Override allow_failure in your project if you want strict linting.
lint:
  stage: lint
  needs:
    - install
  script:
    - echo "Running linter..."
    - bun run lint
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# ------------------------------------------------------------------------------
# Test Stage
# ------------------------------------------------------------------------------
# Runs tests with coverage reporting.
# Coverage regex extracts percentage from standard coverage output formats.
test:
  stage: test
  needs:
    - install
  script:
    - echo "Running tests..."
    - bun test --coverage
  # Coverage regex for common formats (Istanbul, Jest, Vitest)
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

# ------------------------------------------------------------------------------
# Build Stage
# ------------------------------------------------------------------------------
# Builds the project for production deployment.
# Artifacts are retained for 1 week by default.
build:
  stage: build
  needs:
    - install
    - job: test
      optional: true
  script:
    - echo "Building project..."
    - bun run build
    - echo "Build completed successfully"
  artifacts:
    paths:
      - dist/
      - build/
      - .output/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

# ------------------------------------------------------------------------------
# Deploy Template
# ------------------------------------------------------------------------------
# Hidden job template for deployments. Extend in your project:
#
#   deploy-production:
#     extends: .deploy
#     script:
#       - bun run deploy
#     environment:
#       name: production
#       url: https://myapp.example.com
#
.deploy:
  stage: deploy
  needs:
    - build
  script:
    - echo "Override this script in your project"
    - echo "Example: bun run deploy"
  environment:
    name: $CI_COMMIT_REF_SLUG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: $CI_COMMIT_TAG
      when: manual

# ------------------------------------------------------------------------------
# Utility Templates
# ------------------------------------------------------------------------------

# Template for jobs that should only run on merge requests
.merge_request_only:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Template for jobs that should only run on the default branch
.default_branch_only:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Template for jobs that should only run on tags
.tags_only:
  rules:
    - if: $CI_COMMIT_TAG
