# GitLab CI/CD Template: Security Scanning
# ==========================================
# Comprehensive security scanning including SAST, dependency audit, and secrets detection.
# Designed to integrate with kai-security-tools for enhanced scanning capabilities.
#
# Usage:
#   include:
#     - project: 'your-group/kai-gitlab-skill'
#       ref: main
#       file: '/Templates/security-scan.yml'
#
# Variables:
#   SECURITY_FAIL_ON     - Minimum severity to fail the pipeline (critical, high, medium, low)
#   SECURITY_ALLOW_FAIL  - Set to "true" to allow security jobs to fail without blocking
#
# Reports are generated in GitLab-compatible formats for Security Dashboard integration.

stages:
  - security

variables:
  SECURITY_FAIL_ON: "critical"
  SECURITY_ALLOW_FAIL: "true"

# ------------------------------------------------------------------------------
# Dependency Audit
# ------------------------------------------------------------------------------
# Scan project dependencies for known vulnerabilities

# Node.js/Bun dependency audit
dependency-audit-node:
  stage: security
  image: oven/bun:1
  script:
    - echo "Running Node.js dependency audit..."
    - |
      # Try bun audit first, fall back to npm
      if [ -f "bun.lockb" ]; then
        bun audit --level ${SECURITY_FAIL_ON} --json > audit-results.json 2>&1 || true
      elif [ -f "package-lock.json" ]; then
        npm audit --audit-level=${SECURITY_FAIL_ON} --json > audit-results.json 2>&1 || true
      elif [ -f "yarn.lock" ]; then
        yarn audit --level ${SECURITY_FAIL_ON} --json > audit-results.json 2>&1 || true
      fi
    # Convert to GitLab format
    - |
      cat > gl-dependency-scanning-report.json << 'SCRIPT'
      {
        "version": "15.0.0",
        "vulnerabilities": [],
        "dependency_files": []
      }
      SCRIPT
    - cat audit-results.json || true
  allow_failure: true
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
    paths:
      - audit-results.json
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - exists:
        - package.json
        - bun.lockb
        - package-lock.json
        - yarn.lock

# Python dependency audit
dependency-audit-python:
  stage: security
  image: python:3.12-slim
  script:
    - echo "Running Python dependency audit..."
    - pip install safety pip-audit
    - |
      if [ -f "requirements.txt" ]; then
        pip-audit -r requirements.txt --format json --output audit-results.json || true
        safety check -r requirements.txt --json > safety-results.json || true
      elif [ -f "pyproject.toml" ]; then
        pip install poetry
        poetry export -f requirements.txt --output /tmp/requirements.txt
        pip-audit -r /tmp/requirements.txt --format json --output audit-results.json || true
      fi
    - cat audit-results.json || true
  allow_failure: true
  artifacts:
    paths:
      - audit-results.json
      - safety-results.json
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - exists:
        - requirements.txt
        - pyproject.toml
        - Pipfile.lock

# ------------------------------------------------------------------------------
# Secrets Detection
# ------------------------------------------------------------------------------
# Scan for accidentally committed secrets and credentials

secrets-scan:
  stage: security
  image: trufflesecurity/trufflehog:latest
  script:
    - echo "Scanning for secrets with TruffleHog..."
    - |
      trufflehog git file://. \
        --fail \
        --json \
        --only-verified \
        2>&1 | tee trufflehog-results.json || true
    # Convert to GitLab format
    - |
      cat > gl-secret-detection-report.json << 'EOF'
      {
        "version": "15.0.0",
        "vulnerabilities": []
      }
      EOF
  allow_failure: true
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json
    paths:
      - trufflehog-results.json
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Alternative: Gitleaks for secrets scanning
secrets-scan-gitleaks:
  stage: security
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - echo "Scanning for secrets with Gitleaks..."
    - |
      gitleaks detect \
        --source . \
        --report-format json \
        --report-path gitleaks-results.json \
        --exit-code 0
    - cat gitleaks-results.json
  allow_failure: true
  artifacts:
    paths:
      - gitleaks-results.json
    expire_in: 1 week
  rules:
    - if: $SECRETS_SCANNER == "gitleaks"
    - when: never

# ------------------------------------------------------------------------------
# Static Application Security Testing (SAST)
# ------------------------------------------------------------------------------
# Analyze source code for security vulnerabilities

sast-semgrep:
  stage: security
  image: returntocorp/semgrep:latest
  script:
    - echo "Running Semgrep SAST scan..."
    - |
      semgrep scan \
        --config auto \
        --json \
        --output semgrep-results.json \
        --severity ERROR \
        . || true
    - cat semgrep-results.json
  allow_failure: true
  artifacts:
    paths:
      - semgrep-results.json
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# CodeQL analysis (if enabled)
sast-codeql:
  stage: security
  image: mcr.microsoft.com/cstsectools/codeql-container:latest
  script:
    - echo "Running CodeQL analysis..."
    - |
      codeql database create codeql-db --language=${CODEQL_LANGUAGE:-javascript}
      codeql database analyze codeql-db \
        --format=sarif-latest \
        --output=codeql-results.sarif
  allow_failure: true
  artifacts:
    paths:
      - codeql-results.sarif
    expire_in: 1 week
  rules:
    - if: $ENABLE_CODEQL == "true"
    - when: never

# ------------------------------------------------------------------------------
# License Compliance
# ------------------------------------------------------------------------------
# Scan dependencies for license compliance issues

license-scan:
  stage: security
  image: node:20-alpine
  script:
    - echo "Scanning for license compliance..."
    - npm install -g license-checker
    - |
      if [ -f "package.json" ]; then
        license-checker --json --out licenses.json
        # Check for problematic licenses
        license-checker --failOn "GPL;AGPL;LGPL" || true
      fi
  allow_failure: true
  artifacts:
    paths:
      - licenses.json
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - exists:
        - package.json

# ------------------------------------------------------------------------------
# kai-security-tools Integration
# ------------------------------------------------------------------------------
# Enhanced scanning using kai-security-tools pack

kai-security-full-scan:
  stage: security
  image: oven/bun:1
  variables:
    KAI_SECURITY_TOOLS_PATH: "${CI_PROJECT_DIR}/../kai-security-tools"
  script:
    - echo "Running kai-security-tools full scan..."
    - |
      # Check if kai-security-tools is available
      if [ -d "${KAI_SECURITY_TOOLS_PATH}" ]; then
        cd ${KAI_SECURITY_TOOLS_PATH}/Tools
        bun run security-scan.ts \
          --target ${CI_PROJECT_DIR} \
          --format gitlab-ci \
          --output ${CI_PROJECT_DIR}/kai-security-report.json
      else
        echo "kai-security-tools not found, skipping enhanced scan"
        echo '{"status": "skipped", "reason": "kai-security-tools not available"}' > kai-security-report.json
      fi
  allow_failure: true
  artifacts:
    paths:
      - kai-security-report.json
    expire_in: 1 week
  rules:
    - if: $ENABLE_KAI_SECURITY == "true"
    - when: never

# ------------------------------------------------------------------------------
# Security Summary
# ------------------------------------------------------------------------------
# Aggregate and report security findings

security-summary:
  stage: security
  image: alpine:latest
  needs:
    - job: dependency-audit-node
      optional: true
    - job: dependency-audit-python
      optional: true
    - job: secrets-scan
      optional: true
    - job: sast-semgrep
      optional: true
  script:
    - echo "=== Security Scan Summary ==="
    - echo ""
    - |
      # Count findings from each scanner
      echo "Dependency Audit:"
      if [ -f "audit-results.json" ]; then
        cat audit-results.json | head -20
      else
        echo "  No results"
      fi

      echo ""
      echo "Secrets Detection:"
      if [ -f "trufflehog-results.json" ]; then
        cat trufflehog-results.json | head -20
      else
        echo "  No secrets found"
      fi

      echo ""
      echo "SAST (Semgrep):"
      if [ -f "semgrep-results.json" ]; then
        cat semgrep-results.json | head -20
      else
        echo "  No results"
      fi
    - echo ""
    - echo "=== End Security Summary ==="
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# ------------------------------------------------------------------------------
# GitLab Built-in Security Templates
# ------------------------------------------------------------------------------
# Include GitLab's official security scanning templates
# Uncomment the templates you want to use

# SAST using GitLab's built-in scanner
include:
  - template: Security/SAST.gitlab-ci.yml
  # - template: Security/Secret-Detection.gitlab-ci.yml
  # - template: Security/Dependency-Scanning.gitlab-ci.yml
  # - template: Security/License-Scanning.gitlab-ci.yml
  # - template: Security/Container-Scanning.gitlab-ci.yml
