// Generated by scripts/gen-mobile-routes.ts — do not edit.
// The mobile interface renders the desktop component itself; this file
// exists only so Next gives the route its own JS chunk.
export { default } from "@/app/conduit/page";
