// Generated by scripts/gen-mobile-routes.ts — do not edit.
// One static route per TELOS section. NOT a dynamic [section] route:
// that variant hydrated into a client-side exception on every section.
"use client";

import TelosSectionView from "@/components/mobile/TelosSectionView";

export default function Page() {
  return <TelosSectionView slug="problems" />;
}
