name: Dependency Audit

on:
  workflow_call:
    inputs:
      fail-on:
        description: 'Minimum severity to fail on (critical, high, medium, low)'
        required: false
        type: string
        default: 'high'
      working-directory:
        description: 'Directory to scan'
        required: false
        type: string
        default: '.'

permissions:
  contents: read
  security-events: write

jobs:
  audit:
    name: Audit Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Checkout security tools
        uses: actions/checkout@v4
        with:
          repository: your-org/kai-security-tools
          path: .github/security-tools
          # If private repo, add token:
          # token: ${{ secrets.SECURITY_TOOLS_TOKEN }}

      - name: Install security tools dependencies
        run: bun install
        working-directory: .github/security-tools

      # Setup language-specific tools as needed
      - name: Setup Node.js (for npm/pnpm/yarn projects)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        if: hashFiles('package.json', 'package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') != ''

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
        if: hashFiles('pnpm-lock.yaml') != ''

      - name: Setup Python (for pip/poetry projects)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        if: hashFiles('requirements.txt', 'pyproject.toml', 'poetry.lock') != ''

      - name: Install pip-audit
        run: pip install pip-audit
        if: hashFiles('requirements.txt', 'pyproject.toml', 'poetry.lock') != ''

      - name: Setup Rust (for cargo projects)
        uses: dtolnay/rust-toolchain@stable
        if: hashFiles('Cargo.toml', 'Cargo.lock') != ''

      - name: Install cargo-audit
        run: cargo install cargo-audit
        if: hashFiles('Cargo.toml', 'Cargo.lock') != ''

      - name: Setup Go (for go projects)
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        if: hashFiles('go.mod', 'go.sum') != ''

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        if: hashFiles('go.mod', 'go.sum') != ''

      - name: Run dependency audit
        id: audit
        run: |
          bun run .github/security-tools/Tools/DependencyAudit.ts \
            --fail-on=${{ inputs.fail-on }} \
            --sarif \
            ${{ inputs.working-directory }} > dependency-audit.sarif
        continue-on-error: true

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: dependency-audit.sarif
          category: dependency-audit
        if: always()

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-audit-sarif
          path: dependency-audit.sarif
          retention-days: 30
        if: always()

      - name: Print human-readable results
        run: |
          echo "## Dependency Audit Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          bun run .github/security-tools/Tools/DependencyAudit.ts \
            ${{ inputs.working-directory }} >> $GITHUB_STEP_SUMMARY 2>&1 || true
        if: always()

      - name: Check audit result
        if: steps.audit.outcome == 'failure'
        run: |
          echo "Dependency audit found vulnerabilities at or above ${{ inputs.fail-on }} severity"
          exit 1
