name: Secrets Scan

on:
  workflow_call:
    inputs:
      baseline-file:
        description: 'Path to baseline file for ignoring false positives'
        required: false
        type: string
        default: '.secretsignore'
      working-directory:
        description: 'Directory to scan'
        required: false
        type: string
        default: '.'

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch full history to scan all commits in PR
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Checkout security tools
        uses: actions/checkout@v4
        with:
          repository: your-org/kai-security-tools
          path: .github/security-tools
          # If private repo, add token:
          # token: ${{ secrets.SECURITY_TOOLS_TOKEN }}

      - name: Install security tools dependencies
        run: bun install
        working-directory: .github/security-tools

      - name: Run secrets scan
        id: secrets
        run: |
          BASELINE_ARG=""
          if [ -f "${{ inputs.baseline-file }}" ]; then
            BASELINE_ARG="--baseline=${{ inputs.baseline-file }}"
          fi

          bun run .github/security-tools/Tools/SecretsScan.ts \
            --sarif \
            $BASELINE_ARG \
            ${{ inputs.working-directory }} > secrets-scan.sarif
        continue-on-error: true

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: secrets-scan.sarif
          category: secrets-scan
        if: always()

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets-scan-sarif
          path: secrets-scan.sarif
          retention-days: 30
        if: always()

      - name: Print human-readable results
        run: |
          BASELINE_ARG=""
          if [ -f "${{ inputs.baseline-file }}" ]; then
            BASELINE_ARG="--baseline=${{ inputs.baseline-file }}"
          fi

          echo "## Secrets Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          bun run .github/security-tools/Tools/SecretsScan.ts \
            $BASELINE_ARG \
            ${{ inputs.working-directory }} >> $GITHUB_STEP_SUMMARY 2>&1 || true
        if: always()

      # Scan git history for secrets in PR commits
      - name: Scan PR commits for secrets
        if: github.event_name == 'pull_request'
        run: |
          echo "## Scanning PR Commits" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Get the range of commits in the PR
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          # Check each commit's diff
          SECRETS_FOUND=0
          for COMMIT in $(git rev-list $BASE_SHA..$HEAD_SHA); do
            echo "Checking commit $COMMIT..."
            DIFF=$(git show $COMMIT --format="" --name-only)

            for FILE in $DIFF; do
              if [ -f "$FILE" ]; then
                # Run secrets scan on changed file
                RESULT=$(bun run .github/security-tools/Tools/SecretsScan.ts "$FILE" 2>&1) || true
                if echo "$RESULT" | grep -q "secrets detected"; then
                  echo "- :warning: Potential secret in commit $COMMIT: $FILE" >> $GITHUB_STEP_SUMMARY
                  SECRETS_FOUND=1
                fi
              fi
            done
          done

          if [ $SECRETS_FOUND -eq 1 ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo ":rotating_light: **Secrets detected in PR commits!** Please remove them and rotate any exposed credentials." >> $GITHUB_STEP_SUMMARY
          else
            echo ":white_check_mark: No secrets found in PR commits." >> $GITHUB_STEP_SUMMARY
          fi
        continue-on-error: true

      - name: Check secrets scan result
        if: steps.secrets.outcome == 'failure'
        run: |
          echo "Secrets scan found potential leaked secrets"
          echo ""
          echo "If these are false positives, add them to your .secretsignore file"
          exit 1
