/**
 * Automation Module Types
 *
 * Types for market monitoring, job scheduling, and morning briefs.
 */

import type { PositionWithValue, PortfolioState } from 'jai-finance-core';

// =============================================================================
// Monitor Types
// =============================================================================

/**
 * Configuration for the market monitor.
 */
export interface MonitorConfig {
  /** Tickers to monitor */
  tickers: string[];
  /** How often to check positions (milliseconds). Default: 60000 (1 minute) */
  checkInterval?: number;
  /** Stop loss threshold as decimal (e.g., 0.08 = 8%). Default from policy. */
  stopLossThreshold?: number;
  /** Target gain threshold as decimal (e.g., 0.20 = 20%). Default from policy. */
  targetThreshold?: number;
  /** Significant move threshold as decimal (e.g., 0.05 = 5%) */
  significantMoveThreshold?: number;
  /** Webhook URL for alerts (Discord, Slack, etc.) */
  alertWebhook?: string;
}

/**
 * Types of alerts the monitor can generate.
 */
export type MonitorAlertType =
  | 'STOP_LOSS_HIT'
  | 'STOP_LOSS_WARNING'
  | 'TARGET_HIT'
  | 'SIGNIFICANT_DROP'
  | 'SIGNIFICANT_GAIN'
  | 'VOLUME_SPIKE'
  | 'PRICE_ALERT';

/**
 * Alert generated by the market monitor.
 */
export interface MonitorAlert {
  /** Type of alert */
  type: MonitorAlertType;
  /** Ticker that triggered the alert */
  ticker: string;
  /** Human-readable message */
  message: string;
  /** Alert-specific data */
  data: MonitorAlertData;
  /** When the alert was generated */
  timestamp: string;
  /** Alert severity */
  severity: 'critical' | 'warning' | 'info';
}

/**
 * Data payload for different alert types.
 */
export interface MonitorAlertData {
  /** Current price */
  currentPrice?: number;
  /** Previous price (for comparison) */
  previousPrice?: number;
  /** Change amount */
  change?: number;
  /** Change percentage */
  changePercent?: number;
  /** Stop loss price that was hit */
  stopLossPrice?: number;
  /** Target price that was hit */
  targetPrice?: number;
  /** Cost basis for position */
  costBasis?: number;
  /** Current unrealized gain/loss */
  unrealizedPnL?: number;
  /** Volume data if relevant */
  volume?: number;
  /** Average volume for comparison */
  avgVolume?: number;
  /** Additional context */
  [key: string]: unknown;
}

// =============================================================================
// Scheduler Types
// =============================================================================

/**
 * Schedule pattern for jobs.
 * Supports simple patterns like:
 * - 'daily:0800' - Run daily at 8:00 AM
 * - 'daily:1630' - Run daily at 4:30 PM
 * - 'weekly:MON:0800' - Run weekly on Monday at 8:00 AM
 * - 'hourly' - Run every hour
 * - 'interval:300000' - Run every 5 minutes (in milliseconds)
 */
export type SchedulePattern = string;

/**
 * A scheduled job definition.
 */
export interface ScheduledJob {
  /** Unique identifier for the job */
  id: string;
  /** Human-readable name */
  name: string;
  /** When to run (cron-like pattern) */
  schedule: SchedulePattern;
  /** Function to execute */
  handler: () => Promise<void> | void;
  /** Last time this job ran */
  lastRun?: string;
  /** Next scheduled run time */
  nextRun?: string;
  /** Whether the job is enabled */
  enabled?: boolean;
  /** Job-specific metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Parsed schedule for internal use.
 */
export interface ParsedSchedule {
  type: 'daily' | 'weekly' | 'hourly' | 'interval';
  hour?: number;
  minute?: number;
  dayOfWeek?: number; // 0 = Sunday, 1 = Monday, etc.
  intervalMs?: number;
}

// =============================================================================
// Morning Brief Types
// =============================================================================

/**
 * Configuration for generating morning briefs.
 */
export interface MorningBriefConfig {
  /** Path to portfolio positions file */
  portfolioPath: string;
  /** Path to investment policy file */
  policyPath: string;
  /** Whether to send brief to Discord */
  sendToDiscord?: boolean;
  /** Discord webhook for briefs */
  discordWebhook?: string;
  /** Include overnight market summary */
  includeMarketOverview?: boolean;
  /** Include opportunities from watchlist */
  includeOpportunities?: boolean;
  /** Watchlist tickers to check */
  watchlist?: string[];
}

/**
 * Position summary for the morning brief.
 */
export interface BriefPosition {
  /** Ticker symbol */
  ticker: string;
  /** Number of shares */
  shares: number;
  /** Current price */
  currentPrice: number;
  /** Average cost basis */
  costBasis: number;
  /** Current market value */
  marketValue: number;
  /** Unrealized gain/loss dollars */
  unrealizedPnL: number;
  /** Unrealized gain/loss percent */
  unrealizedPnLPercent: number;
  /** Distance from stop loss (percent) */
  stopLossDistance?: number;
  /** Distance from target (percent) */
  targetDistance?: number;
  /** Any alerts for this position */
  alerts: string[];
}

/**
 * Alert summary for the morning brief.
 */
export interface BriefAlert {
  /** Alert type */
  type: MonitorAlertType | 'POLICY_VIOLATION' | 'EARNINGS_UPCOMING' | 'EX_DIVIDEND';
  /** Ticker symbol */
  ticker: string;
  /** Alert message */
  message: string;
  /** Severity */
  severity: 'critical' | 'warning' | 'info';
  /** Recommended action */
  action?: string;
}

/**
 * Investment opportunity for the morning brief.
 */
export interface BriefOpportunity {
  /** Ticker symbol */
  ticker: string;
  /** Current price */
  currentPrice: number;
  /** Target buy price */
  buyPrice: number;
  /** Distance from buy price (percent) */
  distanceFromBuy: number;
  /** Why this is an opportunity */
  reason: string;
  /** Confidence level */
  confidence: 'high' | 'medium' | 'low';
}

/**
 * Market overview for the morning brief.
 */
export interface MarketOverview {
  /** S&P 500 data */
  sp500: {
    price: number;
    change: number;
    changePercent: number;
  };
  /** NASDAQ data */
  nasdaq: {
    price: number;
    change: number;
    changePercent: number;
  };
  /** Dow Jones data */
  dow: {
    price: number;
    change: number;
    changePercent: number;
  };
  /** VIX (fear index) */
  vix: {
    value: number;
    change: number;
  };
  /** 10-year Treasury yield */
  treasury10Y?: {
    yield: number;
    change: number;
  };
  /** Overall market sentiment */
  sentiment: 'bullish' | 'neutral' | 'bearish';
  /** Key market events */
  events?: string[];
}

/**
 * Complete morning brief output.
 */
export interface MorningBrief {
  /** Date of the brief */
  date: string;
  /** High-level summary */
  summary: string;
  /** Portfolio positions with status */
  positions: BriefPosition[];
  /** Active alerts */
  alerts: BriefAlert[];
  /** Investment opportunities */
  opportunities: BriefOpportunity[];
  /** Market overview */
  marketOverview?: MarketOverview;
  /** Portfolio totals */
  portfolioSummary: {
    totalValue: number;
    totalCost: number;
    unrealizedPnL: number;
    unrealizedPnLPercent: number;
    cashAvailable: number;
    dayChange: number;
    dayChangePercent: number;
  };
  /** Generated timestamp */
  generatedAt: string;
}

// =============================================================================
// Notifier Interface
// =============================================================================

/**
 * Interface for alert notification handlers.
 */
export interface AlertNotifier {
  /** Send an alert */
  notify(alert: MonitorAlert): Promise<void>;
  /** Send multiple alerts */
  notifyBatch(alerts: MonitorAlert[]): Promise<void>;
}

// =============================================================================
// Data Provider Interface
// =============================================================================

/**
 * Interface for market data providers used by automation.
 */
export interface AutomationDataProvider {
  /** Get current quote for a ticker */
  getQuote(ticker: string): Promise<{
    price: number;
    change: number;
    changePercent: number;
    volume: number;
    avgVolume?: number;
  }>;
  /** Get quotes for multiple tickers */
  getQuotes(tickers: string[]): Promise<Map<string, {
    price: number;
    change: number;
    changePercent: number;
    volume: number;
    avgVolume?: number;
  }>>;
  /** Get market index data */
  getIndexData(index: 'SPY' | 'QQQ' | 'DIA' | 'VIX'): Promise<{
    price: number;
    change: number;
    changePercent: number;
  }>;
}
